# Generated by Django 6.1.1 on 2026-09-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('batting_style', models.CharField(max_length=50)),
                ('bowling_type', models.CharField(blank=True, max_length=20, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
