# Generated by Django 6.1.1 on 2026-09-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captained_teams', to='cricket.player')),
                ('players', models.ManyToManyField(related_name='teams', to='cricket.player')),
            ],
        ),
    ]
