# Generated by Django 6.1.1 on 2026-09-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ground', models.CharField(max_length=200)),
                ('ball_type', models.CharField(max_length=20)),
                ('overs', models.PositiveIntegerField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('toss_call', models.CharField(blank=True, max_length=10, null=True)),
                ('toss_result', models.CharField(blank=True, max_length=10, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=10, null=True)),
                ('batting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_batting', to='cricket.team')),
                ('bowling_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_bowling', to='cricket.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team1', to='cricket.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team2', to='cricket.team')),
                ('toss_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='toss_wins', to='cricket.team')),
            ],
        ),
    ]
