# Generated by Django 6.1.1 on 2026-09-15 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.PositiveIntegerField()),
                ('overs', models.PositiveIntegerField()),
                ('current_over', models.PositiveIntegerField(default=0)),
                ('balls_bowled', models.PositiveIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('wickets_fallen', models.PositiveIntegerField(default=0)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_batting', to='cricket.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_bowling', to='cricket.team')),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='innings_as_bowler', to='cricket.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='cricket.match')),
                ('non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='innings_as_non_striker', to='cricket.player')),
                ('striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='innings_as_striker', to='cricket.player')),
            ],
        ),
    ]
