# Generated by Django 6.1.1 on 2026-09-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_innings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.PositiveIntegerField()),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('legal_balls', models.PositiveIntegerField(default=0)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overs_bowled', to='cricket.player')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overs_data', to='cricket.innings')),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.PositiveIntegerField()),
                ('runs', models.PositiveIntegerField(default=0)),
                ('extras', models.PositiveIntegerField(default=0)),
                ('extra_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_legal', models.BooleanField(default=True)),
                ('wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(blank=True, max_length=20, null=True)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_bowled', to='cricket.player')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_as_non_striker', to='cricket.player')),
                ('player_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismissals', to='cricket.player')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_faced', to='cricket.player')),
                ('over', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='cricket.over')),
            ],
        ),
    ]
