# Generated by Django 6.1.1 on 2026-09-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_over_ball'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatsmanStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('dismissal_type', models.CharField(blank=True, max_length=20, null=True)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsman_stats', to='cricket.innings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batsman_stats', to='cricket.player')),
            ],
        ),
        migrations.CreateModel(
            name='BowlerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balls_bowled', models.PositiveIntegerField(default=0)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('wides', models.PositiveIntegerField(default=0)),
                ('no_balls', models.PositiveIntegerField(default=0)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler_stats', to='cricket.innings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bowler_stats', to='cricket.player')),
            ],
        ),
    ]
