# Generated by Django 6.1.1 on 2026-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_batsmanstats_bowlerstats'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ball',
            constraint=models.UniqueConstraint(fields=('over', 'ball_number'), name='unique_ball_per_over'),
        ),
        migrations.AddConstraint(
            model_name='batsmanstats',
            constraint=models.UniqueConstraint(fields=('innings', 'player'), name='unique_batsman_stats_per_innings'),
        ),
        migrations.AddConstraint(
            model_name='bowlerstats',
            constraint=models.UniqueConstraint(fields=('innings', 'player'), name='unique_bowler_stats_per_innings'),
        ),
        migrations.AddConstraint(
            model_name='innings',
            constraint=models.UniqueConstraint(fields=('match', 'innings_number'), name='unique_innings_per_match'),
        ),
        migrations.AddConstraint(
            model_name='over',
            constraint=models.UniqueConstraint(fields=('innings', 'over_number'), name='unique_over_per_innings'),
        ),
    ]
